apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    name: api-deployment
    environment: lab
spec:
  selector:
    matchLabels:
      name: api
  replicas: 2
  template:
    metadata:
      labels:
        name: api
    spec:
      containers:
      - name: api
        image: matheusguizolfi/fastapi:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 8000
